#! /bin/bash
set -e -o pipefail

function usage() {
    echo "$0 <kab filename> <repo> <remotefilename>"
    echo " will publish the file to kOS Studio Server"
}

KABFILE="$1"
REPO="$2"
REMOTEFILENAME="$3"

if [ $# -lt 3 ]; then
  usage
  exit 1
fi

ARTSTORE_FILENAME="$HOME/.kosbuild/artifactstores/${REPO}.json"