name: Create and publish x64 docker image
on:
   workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}/kos_builder-native
    TAG: x64

jobs:
    build-and-push-image:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Login to Container registry
          uses: docker/login-action@v3
          with:
             registry: ${{ env.REGISTRY }}
             username: ${{ github.actor }}
             password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
             images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        - name: Get kOS Tools
          run: |
               docker/kos_gettools

        - name: Build and push Docker image
          uses: docker/build-push-action@v6
          with:
            context: docker
            push: true
            tags: ${{ env.TAG }}
            labels: ${{ steps.meta.outputs.labels }}
