#! /bin/bash
# this script is included in developer secrets files to install ssh key secrets into your docker container.
THIS_SCRIPT=$(realpath "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")

set -e -o pipefail

cd

if [ "$(whoami)" != "root" ]; then
    if [ -d "${THIS_SCRIPT_DIR}/ssh-private" ]; then
       echo "loading ssh keys from secrets"
       mkdir -p "$HOME/.ssh"
       cp -r "${THIS_SCRIPT_DIR}/ssh-private/." "${HOME}/.ssh"
       chmod 700 "${HOME}/.ssh"
    fi
fi
